/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function remove(dirOrFile: string): boolean
export function removeDir(dir: string): boolean
export function removeFile(file: string): boolean
